
/**
 * 
 * autogenerated by solidity-visual-auditor
 * 
 * execute with: 
 *  #> truffle test <path/to/this/test.js>
 * 
 * */
 const { expect } = require("chai");
 const { ethers, waffle} = require("hardhat");
 const provider = waffle.provider;

    describe("Staking", function () {
        let staking, stakingob, owner,user1,user2, user3, user4, user5;
        before(async () => {
        [owner,user1,user2,user3,user4,user5_] = await ethers.getSigners();
    
   
     
        staking = await ethers.getContractFactory("Staking");
        stakingob = await staking.deploy();
        await stakingob.deployed({from:owner.address});
        console.log('Staking',stakingob.address);
    
        });
  

  
});
